routes/web.php
<?php
use App\Http\Controllers\Blog\PostsController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','WelcomeController@index')->name('welcome');

Route::get('blog/posts/{post}',[PostsController::class, 'show'])->name('blog.show');
Route::get('blog/categories/{category}',[PostsController::class, 'category'])->name('blog.category');
Route::get('blog/tags/{tag}',[PostsController::class, 'tag'])->name('blog.tag');

Auth::routes();

Route::middleware(['auth'])->group(function(){
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('categories','CategoriesController');
Route::resource('posts','PostsController');
Route::resource('tags','TagsController');
Route::get('trashed-posts',"PostsController@trashed")->name('trashed-posts.index');
Route::put('restore-post/{post}','PostsController@restore')->name('restore-posts');
});

Route::middleware(['auth','admin'])->group(function(){
 Route::get('users/profile','UsersController@edit')->name('users.edit-profile'); 
 Route::put('users/profile','UsersController@update')->name('users.update-profile');  
 Route::get('users','UsersController@index')->name('users.index');
 Route::post('users/{user}/make-admin','UsersController@makeAdmin')->name('users.make-admin');
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ['name'];

    /**
     * 
     * Create a tag post relationship
     * 
     */
    public function posts(){
        return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Tag;

use Illuminate\Http\Request;

use App\Http\Requests\Tags\CreateTagRequest;
use App\Http\Requests\Tags\UpdateTagsRequest;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
     return view('tags.index')->with('tags',Tag::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTagRequest $request)
    {
        Tag::create([
            'name'=>$request->name
        ]);
        session()->flash('success', 'Tag Created Successfully');
        return redirect(route('tags.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
     return view('tags.create')->with('tag',$tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTagsRequest $request, Tag $tag)
    {
       $tag->update([
           'name'=>$request->name
       ]);
       session()->flash('success', 'Tag Updated Successfully');
       
       return redirect(route('tags.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
         //handle relationship before deleting a tags.
    if($tag->posts->count() > 0){
        session()->flash('error','Tags Cannot be deleted has some post!');
        return redirect()->back();      
         }    
     $tag->delete();
    session()->flash('success','Tag Deleted Successfully');  
    return redirect(route('tags.index'));  
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card card-default">
<div class="card-header">
<h3 class="card-title">
{{isset($tag) ? 'Edit Tag' : 'Create Tag'}}
</h3>
</div>
<div class="card-body">
@include('partials.errors')
<form action="{{isset($tag) ? route('tags.update',$tag->id) : route('tags.store')}}" method="POST">
@csrf
@if(isset($tag))
@method('PUT')
@endif
<div class="form-group">
<label for="name">Name</label>
<input type="text" id="name" class="form-control" name="name" value="{{isset($tag) ? $tag->name:''}}">
</div>
<div class="form-group">
<button class="btn btn-success">
{{isset($tag) ? 'Update Tag' : 'Add Tag'}} 
</button>
</div>
</form>
</div>
</div>
@endsection 

resources/views/tags/index.blade.php
@extends('layouts.app')

@section('content')
<div class="card card-default">
<div class="card-header">
<div class="d-flex justify-content-end">
<a href="{{ route('tags.create') }}" class="btn btn-success">Add Tags</a>
</div>
<h3 class="card-title">Tags</h3>
</div>
<div class="card-body">
@if($tags->count()>0)
<table class="table">
<thead>
<th>Name</th>
<th>Post Count</th>
<th></th>
</thead>
<tbody>
@foreach($tags as $tag)
<tr>
<td>{{$tag->name}}</td>
<td>{{$tag->posts->count()}}</td>
<td>
<a href="{{route('tags.edit', $tag->id)}}" class="btn btn-info btn-sm">Edit</a>
<button class="btn btn-danger btn-sm" onclick="handleDelete({{$tag->id}})">Delete</button>
</td>
</tr>
@endforeach
</tbody>
</table>
<form action="" method="POST" id="deleteTagForm">
@csrf
@method('DELETE')
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Tag</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p class="text-center">Are You Sure You want to Delete this tag?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" data-dismiss="modal">No! Dismiss</button>
        <button type="submit" class="btn btn-danger">Yes! Delete</button>
      </div>
    </div>
  </div>
</div>
</form>
@else
<h3 class="text-center">No! Tags at the moment!~</h3>
@endif
</div>
</div>
@endsection

@section('scripts');
<script>
function handleDelete(id){
 $('#deleteModal').modal('show');
 var form = document.getElementById('deleteTagForm');
 form.action = '/tags/' + id
//  console.log('deleted successfull id is:', form);
}
</script>
@endsection